spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:sport_db
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true